# Generated by Django 5.1.1 on 2024-10-19 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_publiced',
            new_name='is_published',
        ),
    ]
